---
author: "Equipo EDUMER"
format: pdf
editor: visual
---

## Introduction

Since its origins, educational institutions have been related to the idea of social mobility and access to better opportunities. Therefore, the consistent evidence of the high level of social reproduction at the school level represents a threat to the promise of education and a meritocratic system [@bourdieu_reproduction_1990]. A large part of the research in this field at an international level has addressed the extent to which the social origin of students affects their academic results and their life opportunities [@vonhippel_test_2019], confirming that schools have severe difficulties in closing the gaps of origin. Besides this socioeconomic perspective on school opportunities, recent research has addressed to what extent inequalities in the school context are also influencing students' perceptions, beliefs, and attitudes: Are social inequalities perceived at the school context? Are they rejected by the students, particularly those who are worst-off in socioeconomic terms? Or, Is there evidence at the school level that social inequalities are tolerated and even justified? [@batruch_belief_2022; @wiederkehr_belief_2015].

In the present paper, we deal with the justification of social inequalities by eighth-grade students in Chile, a country characterized by a highly stratified educational system. In particular, we focus on market justice preferences [@lane_market_1986], which refer to the preferences for distributing public goods (as health and education) based on criteria such as competition and payment capacity. Although from a rational point of view it could be expected an opposition to market justice by the underprivileged majority, we argue that in a social environment characterized by a promotion of meritocratic ideals - as the school system - would lead to the opposite: a larger market justice preferences.

Given that the school environment has an important focus on performance, achievement and acknowledgment, meritocracy has been one of the principal concepts used for understanding and even for justifying performance differences among students. Meritocracy is a distributive system based on the belief that people should be rewarded and promoted based on their abilities, knowledge, and achievements [@young_rise_1958]. It is often seen as a way to create equal opportunities and fairness, as individuals can rise to positions of power and influence based on their own merit rather than their background or connections. However, some argue that meritocracy can actually lead to tolerating or even justifying social inequalities, as it can create a hierarchy where those who already have resources and advantages are more likely to succeed. In this regard, a great deal of academic research about meritocracy delves into the assessment of to what extent rewards and privileges in society are related to merit, emphasizing the so-called unfulfillable promise of meritocracy [@mijs_stratified_2016]. Complementing this agenda, a second and emerging research area deals with subjective aspects of meritocracy, such as perceptions and beliefs.

\[definición de market justice, welfare marketization, (Lindh)\]

\[contexto Chileno market justice, dar cifras/porcentajes de privatización de salud, educación y pensiones; asociar al tema de la calidad (lo público es peor)\]

The perception of meritocracy refers to how individuals view and understand the concept of meritocracy in their own society [@duru-bellat_who_2012; @castillo_meritocracia_2019]. This perception can vary greatly depending on individual experiences, social, economic, and cultural background. Some people may see meritocracy as a fair and just system that allows anyone to succeed based on their abilities and hard work. In contrast, others may view it as a myth or a cover for existing power dynamics and inequality, serving to maintain and even reinforce inequality [@lampert_meritocratic_2013; @mijs_paradox_2021]. Based in this last perspective, we argue that individuals with a higher perception of meritocracy will show a larger justification of social inequalities, as individual achievement would be seen as rewarded and social policies as less necessary [@batruch_belief_2022].

Most of the research that has related meritocratic beliefs to inequality justification so far has only considered adults, leaving aside the study of how beliefs in this field develop at student age as well as the impact of the school context and the family as the main socialization agencies. Regarding schools, the way in which they deal with unequal conditions of origin has been linked to the *hidden curriculum* [@chafel_schooling_1997], whereby students learn about distributive norms in society and mechanisms of justification of social differences. Based on recent studies that relate school meritocracy to the justification of economic inequalities in the adult population [@batruch_belief_2022; @wiederkehr_belief_2015], the central hypothesis guiding this research is that school-age students with a higher perception of meritocracy - both at school and at the societal level - will show a larger justification of social inequalities, as individual achievement would be seen as appropriately rewarded and social mechanisms for correcting inequalities as less necessary [@batruch_belief_2022].

\~

\[introducir distinción sobre percepción de meritocracia a nivel escolar y a nivel de la sociedad\]

\[resaltar 3 focos de innovación: market justice preferences at school level, relación con meritocracia, y esquema de meritocracia en la escuela y en la sociedad\]

The present paper deals with the association between the perception of meritocracy and the justification of social inequalities, with two main focuses. Firstly, it assesses the justification of social inequalities in social policy domains, such as health, pensions, and education. We argue that individuals who perceive more meritocracy would be more willing to justify better services in these domains for those with higher incomes. Secondly, we focus on the student-age population as we point out that it is possible to track down the origin of meritocratic beliefs (and their consequences) to early socialization processes. To this regard, we take into account the family and the school as two main socialization agencies that play a significant role in the socialization of cultural beliefs by transmitting cultural norms, values, and expectations to young people.
