---
author: "Equipo EDUMER"
editor: visual
---

# Discussion

The previous analyses were aimed at delving into the relationship between perceptions of meritocracy and preferences for market justice among students. Several models estimated how students' beliefs about the rewards for talent and effort in both society and school environments influence their attitudes towards access to social services like health, education, and pensions. The models also examined the impact of students' socioeconomic status and school achievement on these preferences, analyzing whether perceptions of meritocracy moderate these effects. The findings provide insights into the complex interplay between meritocratic beliefs, socioeconomic factors, and attitudes towards social justice.

Hypothesis $H_{1a}$ posited that students who perceive greater meritocracy in society would show stronger preferences for market justice. The results support this hypothesis, indicating a positive relationship between the perception that talent and effort are rewarded in society and the preferences for market justice in access to services such as health, education, and pensions. This finding aligns with previous research suggesting that individuals who believe in a meritocratic system are more likely to justify social inequalities [@batruch_belief_2022; @wiederkehr_belief_2015]. It is noteworthy that among the items measuring meritocratic perception, consistently the one about deservingness shows a larger effect when compared to the ones about talent and effort. Although the three items correlate, there is something distinctive about deservingness that probably encompasses other aspects beyond meritocracy, an aspect to which we will come back in the conclusions. Moving now to hypothesis $H_{1b}$, this is simply a variation of 1a, replacing the perception of meritocracy at society by the one at school. In this case we have only two items of meritocratic perception - unfortunately deservingness was not measured at school level - and the direction of the effects is not as straightforward as in the case of societal meritocracy in $H_{1a}$: positive for talent, but negative for effort. Still, one of the limitation for the comparison between perception of meritocracy and society is the difference of the items' phrasing. Whereas for society the item refers to the extent to to which efforts are rewarded, at school is about the importance of effort, whereby something that is important does not necessarily mean that it is enough to be rewarded. Furthermore, the school-effort item is the one with the lowest variation among all meritocratic items (more than 95% agree or strongly agree), and with the lowest effect size.

Hypothesis $H_2$ proposed that students from higher socioeconomic status families would show stronger preferences for market justice, which is not supported by the results. Although students from families with higher educational levels and more economic resources tend to prefer less market justice, this relationship is not statistically significant. This might be due to the influence of other contextual and cultural factors that modulate attitudes toward market justice [@kohn_social_1963; @kohn_class_1969; @almas_fairness_2017]. Notably, socioeconomic status measured by parental educational level and the number of books at home do not explain variations in market justice preferences, suggesting that other variables, such as market justice preferences of parents, could play an essential role in the attitudinal socialization process. 

Hypothesis $H_3$ held that students from schools with higher socioeconomic status would show stronger preferences for market justice. The results did not confirm this hypothesis since although students from high-status schools tend to prefer more market justice, this result is not statistically significant. This finding, contrary to the existing literature [@jonsson_institutional_2015; @jost_attitudinal_2000], does not allow us to affirm the hypothesis about the role of the school environment, particularly socioeconomic segregation, in influencing attitudes towards market justice and the acceptance of inequalities. One possible explanation is the role of school-level variables not fully captured in our models, such as the school's climate or peer influence. Additionally, the non-significant results may suggest that the effect of school socioeconomic status on market justice preferences is correlated to other factors, such as individual meritocratic beliefs.

Hypothesis $H_x$ [Falta hipótesis school achievement] held that students from schools with higher school achievement would show stronger preferences for market justice, following the argument that such school could foster meritocratic attitudes by showing a larger promotion of talent and effort in order to get better results. Nevertheless, the results show quite the opposite: schools with better academic results (as measured by a national standardized test) show in average less preferences for market justice. This finding is one of the most strongest and consistent throughout the models and it is relevante given the centrality of school performance in educational institutions. One posible explanation of this link is that students in high-achieving schools may be more exposed to discussions and to a deeper understanding about inequality and social justice, leading to a critical perspective towards the weight of market mechanism in the access to social services. 

Hypotheses $H_6$ and $H_7$ proposed that family status would moderate the effect of meritocratic perceptions on market justice preferences. Hypothesis $H_6$ refers to family socioeconomic status, whereby the results show a negative interaction with two of the three perceptual variables at the society level. This means that the positive impact of the perception of social meritocracy on market justice preferences have a lower effect in students with parents with higher education and also in those with more books at home. Something similar occurs with hypothesis $H_7$, where now school level status moderates the effect of meritocracy variables, which in multilevel framework si referred as to cross-level interaction. The negative interaction in this context means that in schools of low socioeconomic levels, the positive effect of the social meritocracy variables on market justice preferences is stronger. These relations indicate that, although those who perceive society as meritocratic have greater preferences towards market justice, this influence is lower among those with a higher socioeconomic level. This finding highlights the complex interaction between socioeconomic status, school context, meritocratic beliefs, and preferences toward market justice. The moderating role of meritocratic perceptions suggests that students' views on social justice are shaped by their socioeconomic background and beliefs about how society rewards effort and talent. This underlines the importance of addressing structural inequalities and individual beliefs in educational and social policies.


# Conclusions

Our research aimed to examine the relationship between the perception of meritocracy and the justification of market justice preferences among eighth-grade students in Chile. Overall, our findings provided mixed evidence regarding our hypotheses. While we found support for some associations, others did not align with our initial expectations.

Future research could leverage the capabilities of longitudinal databases to explore contextual level. For example, statistical models could incorporate contextual information from administrative data sources, allowing for testing hypotheses that include contextual socioeconomic inequality and its dynamics over time. Additionally, this dataset could be used to compare inequality justification across different policy areas, such as health and pensions, and examine how meritocratic perceptions and beliefs affect these areas differently over time. Such studies would provide valuable insights for understanding societal and cultural changes and their impacts on solidarity and social cohesion.

- Performance: ver efecto SIMCE individual

-   Efecto ilustrador de la educación? (esfuerzo -\> redistribución)
