---
format:
  html:
    toc: true
    keep-tex: true
editor: visual
smooth-scroll: true
number-sections: true
bibliography: "input/bib/just-ineq-merit.bib"
csl: "input/bib/apa6.csl"
link-citations: true
mainfont: Times New Roman
---

```{css, echo = FALSE}
.justify {
  text-align: justify !important
}
```

# The socialization of meritocracy and market justice preferences at school {.unnumbered}

Abstract

:::{.justify}
Robert E. Lane proposed the underpinnings of the concept of market justice, which he differentiated from political justice. For him, “it is the genius of the market to stimulate wants without at the same time stimulating a sense of deserving more than one gets” [-Lane (1986); p. 384]. Contrary to the evidence that unequal distribution produces feelings of dissatisfaction, anger, and resentment that might motivate forms of collective action (Greitemeyer & Sagioglou, 2016; Mishra & Carleton, 2015; Séamus A. Power, 2018; Séamus A. Power et al., 2020; Smith et al., 2012), Lane points out that in market settings, social comparisons are more likely to motivate increased effort rather than feelings of acute injustice because individuals attribute outcomes to their actions. In this sense, unequal levels of well-being ought to be, to some extent, a function of their talents and efforts, instead of being based in distributive principles that characterize welfarism, such as need and equality (see Wilson 2003).

:::

